config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :users

  post 'twilio/process_sms' => 'twilio#process_sms'

  post 'pages/show_poll' => 'pages#show_poll'

  namespace :admin do 
    resources :polls do
      collection { post :sort }
    end

    root to: 'dashboard#index'

    post '/polls/new', to: 'polls#create'
    get 'signin', to: 'sessions#new'
    post 'signin', to: 'sessions#create'
    get 'signout', to: 'sessions#destroy', via: 'delete'
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  has_many :votes, dependent: :destroy

  validates :question, presence: true, uniqueness: true
  validates :release_date, presence: true
  validates_uniqueness_of :release_date, on: :create

  scope :admin, -> { where("release_date > ?", Date.today).order('release_date ASC') }

  scope :archive, -> { where('release_date < ?', Date.today).order('release_date DESC') }

  def yes_count
    votes.where(answer: 1).count
  end

  def yes_percent
    percent = ((self.yes_count / votes.count.to_f) * 100)
    percent.nan? ? 0 : percent
  end

  def no_count
    votes.where(answer: 2).count
  end

  def no_percent
    percent = ((self.no_count / votes.count.to_f) * 100)
    percent.nan? ? 0 : percent
  end

  def total_votes
    votes.count
  end

  class << self
    def today_poll
      poll = find_by(release_date: Date.today)
      return "Today's question: #{poll.question} Respond with 'yes' or 'no' to vote." unless poll.nil?
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :votes
  
  before_validation :format_number

  validates :name, presence: true
  validates :phone, presence: true, uniqueness: true

  after_save :subscribe_message

  private

    def format_number
      self.phone = self.phone.gsub(/\D/, "") if self.phone =~ /\D/
      self.phone = '+1' + self.phone
    end

    def subscribe_message
      client = setup_client

      from = Rails.application.secrets.twilio_phone_number

      client.account.messages.create(
        from: from,
        to: self.phone,
        body: "You've been subscribed to Daily Poll! " +
              "#{Poll.today_poll unless Poll.today_poll.nil?} " +
              "If you wish to unsubscribe at any time, just text back 'unsubscribe'."
      )
    end
    
    def setup_client
      Twilio::REST::Client.new(Rails.application.secrets.twilio_sid,
                               Rails.application.secrets.twilio_token)
    end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :poll
  
  validates_uniqueness_of :user_id, scope: :poll_id
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController

  layout 'admin'
  before_action :require_admin_signin!

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  layout 'admin'
  before_action :require_admin_signin!

  def index
    @yesterday_poll = Poll.find_by(release_date: (Date.today - 1.day))
    @today_poll = Poll.find_by(release_date: Date.today) 

    @later_polls = Poll.admin
  end
end

app/controllers/admin/polls_controller.rb
class Admin::PollsController < Admin::ApplicationController
  inherit_resources
  
  def create
    create! { admin_root_path }
  end

  def sort
    current_dates = Poll.admin.pluck(:release_date)

    params[:poll].each_with_index do |id, index|
      poll = Poll.find_by(id: id)
      poll.update(release_date: current_dates[index])
    end

    render json: { dates: current_dates }
  end

  private

    def poll_params
      params.require(:poll).permit(:question, :release_date)
    end

end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  layout 'admin'

  before_action :already_signed_in?, only: [:new, :create]

  def new
  end

  def create
    admin = Admin.where(email: params[:signin][:email]).first
    
    if admin && admin.authenticate(params[:signin][:password])
      session[:admin_id] = admin.id
      redirect_to admin_root_url
    else
      render :new
    end
  end

  def destroy
    session.destroy
    redirect_to admin_root_url
  end

  private

    def already_signed_in?
      if admin_signed_in?
        flash[:alert] = "You are already signed in."
        redirect_to admin_root_url   
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

    def admin_user
      @admin_user ||= Admin.find(session[:admin_id]) if session[:admin_id]
    end

    helper_method :admin_user

    def admin_signed_in?
      !admin_user.nil?
    end

    helper_method :admin_signed_in?

    def require_admin_signin!
      if admin_user.nil?
        flash[:alert] = "You need to sign in or sign up before continuing."
        redirect_to admin_signin_url
      end
    end

    helper_method :require_admin_signin!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @user = User.new
    @latest_poll = Poll.find_by(release_date: (Date.today - 1.day).to_s)
    @polls = Poll.archive
  end

  def show_poll
    @archived_poll = Poll.find_by(question: params[:question])
    render partial: '/pages/poll', locals: { poll: @archived_poll }
  end

end

app/controllers/twilio_controller.rb
require 'twilio-ruby'

class TwilioController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :load_poll, :load_user, :format_response

  def process_sms
    case response
      when 'yes' 
        @vote = @poll.votes.build(answer: 1)
        @vote.user = @user
        @vote.save

        render 'process_sms.xml.erb', :content_type => 'text/xml'

      when 'no'
        @vote = @poll.votes.build(answer: 2)
        @vote.user = @user
        @vote.save

        render 'process_sms.xml.erb', :content_type => 'text/xml'

      when 'unsubscribe'
        render 'unsubscribe.xml.erb', :content_type => 'text/xml'

        @user.destroy

      else
        render 'error.xml.erb', :content_type => 'text/xml'
    end
  end

  private
  
    def load_poll
      @poll = Poll.find_by(release_date: Date.today.to_s)
    end

    def load_user
      @user = User.find_by(phone: params["From"])
    end

    def format_response
      response = params["Body"].downcase.gsub(/\s/, '')
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)

    if @user.save
      render json: { status: 'success', user_count: User.all.count }
    else
      @user = User.new
      @poll = Poll.last
      render json: { status: 'failure' }
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :phone)
    end

end

app/helpers/admins_helper.rb
module AdminsHelper

  def poll_today(poll)
    poll.nil? ? "There's no poll today" : poll.question
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  def previous_poll(poll)
    previous_polls = Poll.where("release_date < ?", poll.release_date)
    previous_polls.empty? ? poll.question : previous_polls.first.question
  end

  def next_poll(poll)
    next_polls = Poll.where('release_date > ?', poll.release_date) 
    if next_polls.empty? || poll.release_date == Date.today - 1.day
      poll.question 
    else 
      next_polls.find_by(release_date: poll.release_date + 1.day).question
    end
  end

  def box_height(yes_no_votes, total_votes)
    if total_votes < 1
      return 0
    else
      380 * yes_no_votes / total_votes
    end
  end

end

app/views/admin/dashboard/index.html.haml
.current-poll
  %h2 Today's Poll
  - unless @today_poll.nil?
    %span.date= @today_poll.release_date.strftime('%_m.%d')
    %span.question{ data: { question_text: "#{@today_poll.question}" } }
      = truncate(@today_poll.question, length: 45, separator: ' ')

.poll-section
  %h2 Manage Polls
  - unless @later_polls.empty?
    .future-polls
      %ul.poll-list{ data: { update_url: "#{ sort_admin_polls_url }"} }
        = render partial: "admin/polls/poll", collection: @later_polls

app/views/admin/polls/_poll.html.haml
= content_tag_for :li, poll do
  %span.date= poll.release_date.strftime('%_m.%d')
  %span.question{ data: { question_text: "#{poll.question}" } }
    = truncate(poll.question, length: 45, separator: ' ')

app/views/admin/polls/new.html.haml
%h1 Create Poll
.question-form
  = simple_form_for [:admin, @poll] do |f|
    = f.input :question, input_html: { placeholder: "Question" }
    = f.input :release_date
    = f.submit

app/views/layouts/admin.html.haml
!!! 5
%html
  %head
    %title
      Daily Poll - Admin

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %link{ href: 'http://fonts.googleapis.com/css?family=Arvo:400,700', rel: 'stylesheet', type: 'text/css' }
    %link{ href: 'http://fonts.googleapis.com/css?family=Open+Sans:400,700,600', rel: 'stylesheet', type: 'text/css' }
    = csrf_meta_tags

%body.admin-body
  %nav
    .container.clearfix
      .navbar-header
        = link_to "Admin Dashboard", admin_root_path, class: 'admin-logo'
      - if admin_signed_in?
        %ul.navlinks.clearfix
          %li
            = link_to "Create Poll", new_admin_poll_path

    - flash.each do |type, msg|
      %p
        = msg

  .container
    = yield

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      Daily Poll
    
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = favicon_link_tag 'favicon.ico'

    = csrf_meta_tags
    %link{ href: 'http://fonts.googleapis.com/css?family=Arvo:400,700', rel: 'stylesheet', type: 'text/css' }
    %link{ href: 'http://fonts.googleapis.com/css?family=Open+Sans:400,700,600', rel: 'stylesheet', type: 'text/css' }
    %meta{ name: "viewport", content: "initial-scale=1, maximum-scale=1" }

%body

  - flash.each do |type, msg|
    %p= msg
  = yield

app/views/pages/_archive.html.haml
- unless polls.empty?
  .archive-container
    .archive-content
      %h1 the archive
      .archive-index
        %ul
          - polls.each do |poll|
            %li.clearfix
              %span.date= poll.release_date.strftime('%_m.%d')
              %span.question{ data: { question_text: "#{poll.question}" } }
                = truncate(poll.question, length: 48, separator: ' ')
      - if @latest_poll
        .archive-poll-container
          .archive-poll
            .poll-scroll
              .previous-poll{data: {previous_poll: previous_poll(@latest_poll)}}
                %span prev
              .next-poll{data: {next_poll: next_poll(@latest_poll)}}
                %span next
            = render partial: 'poll', locals: { poll: @latest_poll }

app/views/pages/_archive_poll_scroll.html.haml
.poll-scroll
  .previous-poll
    %span prev
  .next-poll
    %span next

app/views/pages/_footer.html.haml
.footer
  .new-user-form
    %h1
      = "Join #{User.all.count} others on Daily Poll"
    = render partial: '/users/form', locals: {resource: @user}
  .clear

app/views/pages/_poll.html.haml
.poll
  .previous-poll-data{data: {previous_poll: previous_poll(poll)}}
  .next-poll-data{data: {next_poll: next_poll(poll)}}
  .question
    %span
      =poll.question
  .people
    - poll.yes_percent.to_i.times do
      = image_tag("single_cheering_blue.png")
    - (100 - poll.yes_percent.to_i).times do
      = image_tag("single_cheering_red.png")
  .poll-stats-container
    .yes-percent
      = number_to_percentage(poll.yes_percent, precision: 0)
      %br/
      YES
    .no-percent
      = number_to_percentage(poll.no_percent, precision: 0)
      %br/
      NO
    .count-container
      .yes-count
        %span.yes YES:
        %span.count= "#{poll.yes_count}"
      .no-count
        %span.no NO:
        %span.count= "#{poll.no_count}"
      .total-votes
        %span.total TOTAL VOTES:
        %span.total-count= "#{poll.total_votes}"

app/views/pages/_poll_stats.html.haml
.question
  %span 
    =poll.question
.people
  - poll.yes_percent.to_i.times do
    = image_tag("single_cheering_blue.png")
  - poll.no_percent.to_i.times do 
    = image_tag("single_cheering_red.png")
.poll-stats-container
  .yes-percent
    = number_to_percentage(poll.yes_percent, precision: 0)
    %br/
    YES
  .no-percent
    = number_to_percentage(poll.no_percent, precision: 0)
    %br/ 
    NO
  .count-container
    .yes-count
      %span.yes YES:
      %span.count= "#{poll.yes_count}"
    .no-count
      %span.no NO:
      %span.count= "#{poll.no_count}"
    .total-votes
      %span.total TOTAL VOTES:
      %span.total-count= "#{poll.total_votes}"

app/views/pages/_question.html.haml
.latest-question
  %h2 the latest question
  - if poll.nil?
    No polls yet!
  - else
    .question-header
      %h1= poll.question

    .results
      .result-set
        %span.vote-count.total
          = poll.votes.count
        %p total votes
      .result-set
        %span.vote-count.yes
          = poll.yes_count
        %p voted YES
      .result-set
        %span.vote-count.no
          = poll.no_count
        %p voted NO

    .chart

      .yes-section-container
        .yes-people-box
          .yes-people{ :style => "height: #{100 - poll.yes_percent }%;"}
            %h2 YES!
            = image_tag("cheering_blue.png")
        .yes-graph
          .yes-box{:style => "height: #{box_height(poll.yes_count, poll.votes.count)}px;"}
            %span= number_to_percentage(poll.yes_percent, precision: 0)
      .no-section-container
        .no-people-box
          .no-people{ :style => "height: #{100 - poll.no_percent }%;"}
            %h2 NO!
            = image_tag("cheering_red.png")
        .no-graph
          .no-box{:style => "height: #{box_height(poll.no_count, poll.votes.count)}px;"}
            %span= number_to_percentage(poll.no_percent, precision: 0)

app/views/pages/_signup.html.haml
.content
  .header
    %h1.logo Daily Poll
  .signup-content-wrapper.clearfix
    .sub-header-wrapper
      .sub-header
        %h2 Are you part of the majority or the minority? Answer a daily question via SMS and find out!
      .speech-bubble-bottom
    .cheering-main-and-form-wrapper
      .cheering-main
        = image_tag("cheering_main.png")
      .new-user-form-wrapper
        .new-user-form.clearfix
          = render partial: '/users/form', locals: {resource: @user}

app/views/pages/home.html.haml
.pages-signup-container
  = render partial: 'signup'
.pages-question-container
  = render partial: 'question', locals: { poll: @latest_poll }
.pages-archive-container
  = render partial: 'archive', locals: { polls: @polls }
.pages-footer-container
  = render partial: 'footer'

app/views/pages/question_stats.html.haml
.question
      %span 
        =poll.question
    .people
      - poll.yes_percent.to_i.times do
        = image_tag("single_cheering_blue.png")
      - poll.no_percent.to_i.times do 
        = image_tag("single_cheering_red.png")
    .poll-stats-container
      .yes-percent
        = number_to_percentage(poll.yes_percent, precision: 0)
        %br/
        YES
      .no-percent
        = number_to_percentage(poll.no_percent, precision: 0)
        %br/ 
        NO
      .count-container
        .yes-count
          %span.yes YES:
          %span.count= "#{poll.yes_count}"
        .no-count
          %span.no NO:
          %span.count= "#{poll.no_count}"
        .total-votes
          %span.total TOTAL VOTES:
          %span.total-count= "#{poll.total_votes}"

app/views/twilio/error.xml.erb
<Response>
  <Sms>Sorry, we don't understand that response.</Sms>
</Response>

app/views/twilio/process_sms.xml.erb
<Response>
  <Sms>Thanks for voting! Check out the results tomorrow on dailypoll.nycdevshop.com!</Sms>
</Response>

app/views/twilio/unsubscribe.xml.erb
<Response>
  <Sms>You've been unsubscribed.</Sms>
</Response>

app/views/users/_form.html.haml
= simple_form_for @user do |f|
  = f.input :name, required: false, input_html: { placeholder: "Name" }
  = f.input :phone, required: false, input_html: { placeholder: "Phone Number" }
  = f.submit "Subscribe"